---

- name: Configure firewall - FORWARD / NAT
  template:
    src: 'etc/ferm/ferm.d/subnetwork.conf.j2'
    dest: '/etc/ferm/ferm.d/subnetwork_{{ subnetwork_iface }}.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]

